`timescale 1ns / 1ps

module matlab_reverb_tb;

    // --- Parameters (Matching MATLAB & RTL Configuration) ---
    localparam int AUDIO_WIDTH   = 32;
    localparam int ADDR_WIDTH    = 10;
    localparam int ACC_WIDTH     = 32;
    localparam int NUM_SAMPLES   = 1024;
    localparam int DELAY_SAMPLES = 811; // Prime number delay

    // --- Signals ---
    logic clk, rst_n, en;
    logic [ACC_WIDTH-1:0] tuning_word;
    logic signed [AUDIO_WIDTH-1:0] saw_raw;
    logic signed [AUDIO_WIDTH-1:0] reverb_out;

    // --- Golden Reference Memory ---
    logic [AUDIO_WIDTH-1:0] input_golden_ref  [0:NUM_SAMPLES-1];
    logic [AUDIO_WIDTH-1:0] reverb_golden_ref [0:NUM_SAMPLES-1];

    // Error Tracking
    int input_errors  = 0;
    int reverb_errors = 0;
    int fd_out;
    
    // Path for ECE AFS Servers
    string path = "/afs/ece.cmu.edu/usr/shayaang/Private/18500/MatlabSim/Effects/SV_Verification/";
    string hex_path = "/afs/ece.cmu.edu/usr/shayaang/Private/18500/Effects/Matlab_Verification/Matlab_Hex/";

    // --- 1. Instantiate Audio Source (Sawtooth Oscillator) ---
    osc_saw #(
        .ACC_WIDTH(ACC_WIDTH), 
        .OUT_WIDTH(AUDIO_WIDTH)
    ) audio_src (
        .clk(clk), 
        .rst_n(rst_n), 
        .tuning_word(tuning_word), 
        .enable(en), 
        .saw_out(saw_raw)
    );

    // --- 2. Instantiate Reverb (DUT) ---
    reverb #(
        .AUDIO_WIDTH(AUDIO_WIDTH),
        .ADDR_WIDTH(ADDR_WIDTH),
        .DELAY_SAMPLES(DELAY_SAMPLES)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .en(en),
        .signal_in(saw_raw),
        .signal_out(reverb_out)
    );

    // --- 3. Clock and Enable Generation ---
    initial begin clk = 0; forever #5 clk = ~clk; end

    // 48kHz Sample Clock Pulse
    initial begin
        en = 0;
        forever begin
            #(20833); @(posedge clk); en = 1;
            @(posedge clk); en = 0;
        end
    end

    // --- 4. Main Verification Sequence ---
    initial begin
        // Load Hex Files generated by MATLAB
        $readmemh({hex_path, "effect_input_saw_golden.hex"}, input_golden_ref);
        $readmemh({hex_path, "reverb_golden.hex"}, reverb_golden_ref);

        // Open Log
        fd_out = $fopen({path, "sv_reverb_out.txt"}, "w");
        if (!fd_out) begin
            $display("FATAL: Could not open output log file.");
            $finish;
        end

        // Initial state
        rst_n = 0;
        tuning_word = 32'd39370534; // 440Hz @ 48kHz
        #100 rst_n = 1;

        $display("--- Starting REVERB Verification ---");
        $display("Feedback Comb Filter | Delay: %0d samples", DELAY_SAMPLES);

        for (int i = 0; i < NUM_SAMPLES; i++) begin
            @(posedge en);
            @(negedge clk); // Sample state after registers update

            // Log output for manual debug
            $fdisplay(fd_out, "%08h", reverb_out);

            // 1. Verify Audio Input Source
            if (saw_raw !== input_golden_ref[i]) begin
                $display("[INPUT ERR] Sample %0d | RTL Saw: %h | Golden: %h", i, saw_raw, input_golden_ref[i]);
                input_errors++;
            end

            // 2. Verify Reverb Output
            if (reverb_out !== reverb_golden_ref[i]) begin
                $display("[REVERB ERR] Sample %0d | RTL: %h | Golden: %h", i, reverb_out, reverb_golden_ref[i]);
                reverb_errors++;
            end
        end

        // Final Report
        $display("\n--- REVERB Verification Report ---");
        $display("Input Mismatches: %0d", input_errors);
        $display("Reverb Mismatches: %0d", reverb_errors);
        
        if ((input_errors + reverb_errors) == 0)
            $display("SUCCESS: Reverb matches Golden Reference.");
        else
            $display("FAILURE: Check feedback attenuation or saturation logic.");

        $fclose(fd_out);
        $finish;
    end

endmodule