`timescale 1ns / 1ps

module matlab_echo_tb;

    // --- Parameters (Matching MATLAB Generation) ---
    localparam int AUDIO_WIDTH = 32;
    localparam int ADDR_WIDTH  = 10;
    localparam int ACC_WIDTH   = 32;
    localparam int NUM_SAMPLES = 1024;

    // --- Signals ---
    logic clk, rst_n, en;
    logic [ACC_WIDTH-1:0] tuning_word;
    logic signed [AUDIO_WIDTH-1:0] saw_raw;
    logic signed [AUDIO_WIDTH-1:0] echo_out;

    // --- Golden Reference Memory ---
    logic [AUDIO_WIDTH-1:0] input_golden_ref [0:NUM_SAMPLES-1];
    logic [AUDIO_WIDTH-1:0] echo_golden_ref  [0:NUM_SAMPLES-1];

    // Error Tracking
    int input_errors = 0;
    int echo_errors  = 0;
    int fd_out;
    
    // Path for ECE AFS Servers
    string path = "/afs/ece.cmu.edu/usr/shayaang/Private/18500/MatlabSim/Effects/SV_Verification/";
    string hex_path = "/afs/ece.cmu.edu/usr/shayaang/Private/18500/Effects/Matlab_Verification/Matlab_Hex/";

    // --- 1. Instantiate Sawtooth Oscillator (Input Source) ---
    osc_saw #(
        .ACC_WIDTH(ACC_WIDTH), 
        .OUT_WIDTH(AUDIO_WIDTH)
    ) osc_inst (
        .clk(clk), 
        .rst_n(rst_n), 
        .tuning_word(tuning_word), 
        .enable(en), 
        .saw_out(saw_raw)
    );

    // --- 2. Instantiate Echo (DUT) ---
    echo #(
        .AUDIO_WIDTH(AUDIO_WIDTH),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .en(en),
        .signal_in(saw_raw),
        .signal_out(echo_out) // This wire is now actively driven!
    );

    // --- 3. Clock and Enable Generation ---
    initial begin clk = 0; forever #5 clk = ~clk; end

    // 48kHz Sample Clock Pulse
    initial begin
        en = 0;
        forever begin
            #(20833); @(posedge clk); en = 1;
            @(posedge clk); en = 0;
        end
    end

    // --- 4. Main Verification Sequence ---
    initial begin
        // Load Hex Files generated by MATLAB
        $readmemh({hex_path, "effect_input_saw_golden.hex"}, input_golden_ref);
        $readmemh({hex_path, "echo_golden.hex"}, echo_golden_ref);

        // Open Log
        fd_out = $fopen({path, "sv_echo_out.txt"}, "w");
        if (!fd_out) begin
            $display("FATAL: Could not open output log file.");
            $finish;
        end

        // Initial state
        rst_n = 0;
        tuning_word = 32'd39370534; // 440Hz @ 48kHz
        #100 rst_n = 1;

        $display("--- Starting ECHO Verification ---");
        $display("Testing Fixed Delay = 512 samples");

        // Note: Hardware has a 1-cycle latency due to internal registers.
        // If MATLAB starts immediately, you might need to align by skipping 
        // the first sample or checking if your MATLAB model is "one cycle ahead".
        
        for (int i = 0; i < NUM_SAMPLES; i++) begin
            @(posedge en);
            @(negedge clk); // Sample after sequential update

            // Log output
            $fdisplay(fd_out, "%08h", echo_out);

            // 1. Verify Oscillator Input matches MATLAB
            if (saw_raw !== input_golden_ref[i]) begin
                $display("[INPUT ERR] Sample %0d | RTL: %h | Golden: %h", i, saw_raw, input_golden_ref[i]);
                input_errors++;
            end

            // 2. Verify Echo Logic matches MATLAB
            if (echo_out !== echo_golden_ref[i]) begin
                $display("[ECHO ERR] Sample %0d | RTL: %h | Golden: %h", i, echo_out, echo_golden_ref[i]);
                echo_errors++;
            end
        end

        // Final Report
        $display("\n--- ECHO Verification Report ---");
        $display("Input Mismatches: %0d", input_errors);
        $display("Echo Mismatches: %0d", echo_errors);
        
        if ((input_errors + echo_errors) == 0)
            $display("SUCCESS: Echo matches Golden Reference.");
        else
            $display("FAILURE: Check RAM read latency or saturation logic.");

        $fclose(fd_out);
        $finish;
    end

endmodule